SigAv/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lote/', include('lote.urls')),
    path('producao/', include('producao.urls')),
    path('', include('producao.urls', namespace='home')),
    path('vacina/', include('vacina.urls')),
    path('usuario/', include('usuario.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
]

lote/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'lote'

urlpatterns = [
    path('criar/', views.criar_lote, name='criar'),
    path('listar/', views.ListarLotes.as_view(), name='listar'),
    path('listar_finalizados/', views.listar_finalizados, name='listar_finalizados'),
    path('editar/<int:pk>', views.EditarLote.as_view(), name='editar'),
    path('deletar/<int:pk>', views.DeletarLote.as_view(), name='deletar'),
    path('detalhes/', views.detalhes, name='detalhes'),
    path('detalhes_finalizado/<int:pk>', views.detalhes_finalizado, name='detalhes_finalizado'),

    path('criar_registro_diario_lote/', views.criar_registro_diario, name='criar_registro_diario'),
    path('editar_registro/<int:pk>/', views.EditarRegistroDiario.as_view(), name='editar_registro'),
    path('deletar_registro/<int:pk>/', views.DeletarRegistroDiario.as_view(), name='deletar_registro'),


    path('alterar_status/', views.alterar_status, name="alterar_status"),
]

producao/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.views.generic import RedirectView

app_name = 'producao'

urlpatterns = [
    path ('', views.home, name='home'),
    path('criar/', views.Criar_Producao.as_view(), name='criar'),
    path('listar/', views.Listar_Producao.as_view(), name='listar'),
    path('editar/<int:pk>', views.Editar_Producao.as_view(), name='editar'),
    path('deletar/<int:pk>', views.Deletar_Producao.as_view(), name='deletar'),
    path('detalhes/<int:pk>', views.detalhes, name='detalhes'),

    path('criar_registro_diario_producao_1/<int:pk>/<int:tipo>', views.criar_registro_diario_1, name='criar_registro_diario_1'),
    path('criar_registro_diario_producao_2/<int:pk>', views.criar_registro_diario_2, name='criar_registro_diario_2'),

    path('editar_registro/<int:pk>/', views.EditarRegistroDiario.as_view(), name='editar_registro'),
    path('deletar_movimento_diario/<int:pk>/', views.DeletarMovimentoDiario.as_view(), name='deletar_movimento_diario'),
 
    path('cadastrar/', views.cadastrar, name='cadastrar'),
    path('alterar_status/<int:pk>', views.alterar_status, name='alterar_status'),

    path('coleta_diaria/<int:pk>', views.coleta_diaria, name='coleta_diaria'),
]

# Coleta dos bolsistas
urlpatterns += [
    path('bolsista_coleta_diaria_1/<int:pk>/<int:tipo>', views.criar_registro_diario_1, name='bolsista_coleta_diaria_1'),
    path('bolsista_coleta_diaria_2/<int:pk>', views.criar_registro_diario_2, name='bolsista_coleta_diaria_2')
]

# url patterns das novas views
urlpatterns += [
    path('bolsista/', views.home_bolsista, name='bolsista'),
    path('', views.home_admin, name='home_admin')
]

lote/models.py
from django.db import models
from datetime import date


APTIDAO = [
    ('A', 'Corte'),
    ('B', 'Postura'),
]

RACA = [
    ('A', 'Lohmann white'),
    ('B', 'Lohmann Brown'),
    ('C', 'Linhagem 3'),
    ('D', 'Linhagem 4'),
]

STATUS = [
    ('A', 'Isolamento'),
    ('B', 'Liberados'),
    ('C', 'Finalizado'),
]


class Lote(models.Model):

    codigo = models.CharField(max_length=50, unique=True)
    aptidao = models.CharField(max_length=1, choices=APTIDAO, default='B')
    data_chegada = models.DateField(default=date.today)
    localidade = models.CharField(max_length=200)
    quantidade_aves_chegada = models.PositiveIntegerField()
    quantidade_aves_final = models.PositiveIntegerField(null=True, blank=True)
    raca = models.CharField(max_length=1, choices=RACA)
    status = models.CharField(max_length=1, choices=STATUS, default='A')

    def __str__(self):
        return self.codigo

    class Meta:
        ordering = ('status', 'data_chegada',)


class Registro_diario_lote(models.Model):

    peso = models.DecimalField(max_digits=10, decimal_places=3, null=True, blank=True)
    mortalidade = models.PositiveIntegerField(default=0)
    lote = models.ForeignKey(Lote, on_delete=models.RESTRICT)
    data = models.DateField(default=date.today)

    def __str__(self):
        return str(self.lote) + " - " + str(self.data)

    class Meta:
        ordering = ('-lote', '-data',)

lote/forms.py
from django.forms import ModelForm
from datetime import date
from django import forms
from django.db.models import Q
from .models import Lote, Registro_diario_lote

class LoteForm(ModelForm):
    class Meta:
        model = Lote
        fields = ['data_chegada', 'localidade', 'aptidao',
                'quantidade_aves_chegada', 'raca']

class RegistroDiarioLoteForm(ModelForm):
    class Meta:
        model = Registro_diario_lote
        fields = ['data', 'mortalidade']

    def clean_data(self):
        data = self.cleaned_data['data']
        lote_atual = Lote.objects.filter(Q(status="A") | Q(status="B"))[0]

        if data > date.today() :
            raise forms.ValidationError("Não é possível realizar um registro para uma data futura.")
        elif (len(Registro_diario_lote.objects.filter(data=data, lote=lote_atual)) > 0):
            raise forms.ValidationError("Já foi adicionado um registro diário neste lote para esta data.")
        return data

lote/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.db.models import Q
from datetime import date
from django.contrib import messages
from datetime import timedelta

import json

from django.views.generic import CreateView, ListView, DeleteView, UpdateView, DetailView
from .models import Lote, Registro_diario_lote
from .forms import LoteForm, RegistroDiarioLoteForm

def criar_lote(request):
    if (request.method == "POST"):
        form = LoteForm(request.POST)
        if (form.is_valid()):
            lote = Lote()
            lote.data_chegada = form.cleaned_data['data_chegada']
            lote.localidade = form.cleaned_data['localidade']
            lote.aptidao = form.cleaned_data['aptidao']
            lote.raca = form.cleaned_data['raca']
            lote.quantidade_aves_chegada = form.cleaned_data['quantidade_aves_chegada']
            lote.quantidade_aves_final = lote.quantidade_aves_chegada

            ano = lote.data_chegada.year
            quantidade_lotes_ano = Lote.objects.filter(data_chegada__year = ano).order_by('-codigo').count()
            lote.codigo = str(ano)+"."+format(quantidade_lotes_ano+1, "03d")
            lote.save()
            messages.success(request, 'Lote ' + lote.codigo + ' criado com sucesso.')
            return redirect('lote:detalhes')
    else:
        if (buscar_lote_atual() is None):
            ano = date.today().year
            quantidade_lotes_ano = Lote.objects.filter(data_chegada__year = ano).order_by('-codigo').count()
            form = LoteForm()
        else:
            messages.error(request, 'Não é possível cadastrar um novo lote de confinamento. ' +
                                        'Há um lote ocupando o espaço. '+
                                        'Transfira os animais para a postura para poder cadastrar um novo lote.')
            return redirect('lote:detalhes')                           
    return render(request, "lote/criar.html", {'form': form, 'codigo': str(ano)+"."+format(quantidade_lotes_ano+1, "03d")})

def criar_registro_diario(request):
    lote_atual = buscar_lote_atual()
    if (request.method == "POST"):
        form = RegistroDiarioLoteForm(request.POST)
        if (form.is_valid()):
            registro_diario = Registro_diario_lote()
            registro_diario.data = form.cleaned_data['data']
            # registro_diario.peso = form.cleaned_data['peso']
            registro_diario.mortalidade = form.cleaned_data['mortalidade']
            registro_diario.lote = lote_atual
            registro_diario.save()

            lote_atual.quantidade_aves_final = lote_atual.quantidade_aves_final - registro_diario.mortalidade
            lote_atual.save()
            return redirect('lote:detalhes')
    else:
        form = RegistroDiarioLoteForm()
    
    informacoes = {
        'form':form,
        'lote': lote_atual
    }
    return render(request, "lote/criar_registro_diario.html", informacoes)

class ListarLotes(ListView):
    model = Lote
    template_name = 'lote/listar.html'
    # lote_list

def listar_finalizados(request):
    lista_lotes = Lote.objects.filter(status="C").order_by('-codigo')
    informacoes = {
        'lista_lotes': lista_lotes
    }
    return render(request, 'lote/listar_finalizados.html', informacoes)

class EditarLote(UpdateView):
    model = Lote
    fields = ['data_chegada', 'localidade', 'aptidao',
                'quantidade_aves_chegada', 'raca']
    template_name = 'lote/editar.html'
    success_url = reverse_lazy('lote:listar')
    # form

class DeletarLote(DeleteView):
    model = Lote
    template_name = 'lote/confirmacao_deletar.html'
    success_url = reverse_lazy('lote:listar')
    # object

class EditarRegistroDiario(UpdateView):
    model = Registro_diario_lote
    fields = ['data', 'mortalidade']
    template_name = 'lote/editar_registro_diario.html'
    success_url = reverse_lazy('lote:detalhes')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lote'] = self.object.lote
        return context

    def form_valid(self, form):
        nova_mortalidade = form.save(commit=False).mortalidade
        mortalidade_anterior = Registro_diario_lote.objects.filter(pk=self.object.pk)[0].mortalidade
        self.object.lote.quantidade_aves_final = self.object.lote.quantidade_aves_final + mortalidade_anterior - nova_mortalidade
        self.object.lote.save()
        return super().form_valid(form)

class DeletarRegistroDiario(DeleteView):
    model = Registro_diario_lote
    success_url = reverse_lazy('lote:detalhes')

    def delete(self, *args, **kwargs):
        self.object = self.get_object()
        self.object.lote.quantidade_aves_final = self.object.lote.quantidade_aves_final + self.object.mortalidade
        self.object.lote.save()
        return super(DeletarRegistroDiario, self).delete(*args, **kwargs)

def detalhes(request):
    lote_atual = buscar_lote_atual()
    registros_diarios = Registro_diario_lote.objects.filter(lote=lote_atual).order_by("-data")
    registros_diarios_graficos = registros_diarios.reverse()
    
    # Informações para o gráfico
    datas_mortalidade = []
    datas_peso = []
    mortalidade = []
    pesos = []

    mortalidade_media, semanas = definir_mortalidade_semanal(registros_diarios_graficos)

    # for i, registro in enumerate(registros_diarios_graficos):
    #     datas_mortalidade.insert(i, str(registro.data))
    #     mortalidade.insert(i, registro.mortalidade)
    #     if (registro.peso != None):
    #         datas_peso.insert(i, str(registro.data))
    #         pesos.insert(i, str(registro.peso))

    # Informações para a tela
    informacoes = {
        'lote': lote_atual,
        'registros_diarios': registros_diarios,
        'datas_mortalidade': json.dumps(semanas),
        'mortalidade': json.dumps(mortalidade_media),
        'datas_peso': json.dumps(datas_peso),
        'pesos': json.dumps(pesos)
    }
    return render(request, "lote/detalhes.html", informacoes)

def detalhes_finalizado(request, pk):
    lote_atual = Lote.objects.get(pk=pk)
    registros_diarios = Registro_diario_lote.objects.filter(lote=lote_atual).order_by("-data")
    registros_diarios_graficos = registros_diarios.reverse()
    
    # Informações para o gráfico
    datas_mortalidade = []
    datas_peso = []
    mortalidade = []
    pesos = []

    for i, registro in enumerate(registros_diarios_graficos):
        datas_mortalidade.insert(i, str(registro.data))
        mortalidade.insert(i, registro.mortalidade)
        if (registro.peso != None):
            datas_peso.insert(i, str(registro.data))
            pesos.insert(i, str(registro.peso))

    informacoes = {
        'lote': lote_atual,
        'registros_diarios': registros_diarios,
        'datas_mortalidade': json.dumps(datas_mortalidade),
        'mortalidade': json.dumps(mortalidade),
        'datas_peso': json.dumps(datas_peso),
        'pesos': json.dumps(pesos)
    }
    return render(request, "lote/detalhes_finalizado.html", informacoes)

def definir_mortalidade_semanal(registros_diarios):
    primeira_data = registros_diarios[0].data

    mortalidade_media = []
    semanas = []

    mortalidade = 0
    quantidade = 0
    semana = 1

    for i, registro in enumerate(registros_diarios):
        if (registro.data > (primeira_data + timedelta(days=6))):
            primeira_data=primeira_data + timedelta(days=7)
            mortalidade_media.append(round(mortalidade/quantidade, 2))
            semanas.append(semana)
            semana = semana + 1
            mortalidade = 0
            quantidade = 0

        mortalidade = mortalidade + registro.mortalidade
        quantidade = quantidade + 1
    
    mortalidade_media.append(round(mortalidade/quantidade, 2))
    semanas.append(semana)
    
    return mortalidade_media, semanas
        

# View alterar_status
def alterar_status(request):
    lote_atual = buscar_lote_atual()
    if (lote_atual.status == "A"):
        lote_atual.status = "B"
    else:
        lote_atual.status = "A"
    lote_atual.save()
    return redirect("lote:detalhes")

def buscar_lote_atual():
    if (len(Lote.objects.filter(Q(status="A") | Q(status="B"))) > 0):
        return Lote.objects.filter(Q(status="A") | Q(status="B"))[0]
    else:
        return None

templates/lote/confirmacao_deletar.html
{% extends "base.html" %}
{% block titulo %}
Deletar registro
{% endblock %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    {% block conteudo %}
    {% load bootstrap4 %}
</head>
<body>
    <div class="container">

        <form method="post">
            {% csrf_token %}
            Lote: {{object}} <br>
            Data: {{object.data_chegada}} <br>
            Localidade: {{object.localidade}} <br>
            <input type="submit" class="btn btn-success" value="Deletar">
        </form>
      </div>
</body>
</html>

{% endblock %}

templates/lote/criar.html
{% extends "base.html" %}
{% block titulo %}
Abertura do Lote {{codigo}}
{% endblock %}

    {% block conteudo %}     
    {% load bootstrap4 %}

        <form method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
            <input type="submit" class="btn btn-success" value="Cadastrar">
        </form>
{% endblock %}

templates/lote/criar_registro_diario.html
{% extends "base.html" %}
{% block titulo %}
Registro diário
<p class="m-0 h5 font-weight-regular text-gray-500">Lote {{lote}}</p>

{% endblock %}

{% block conteudo %}     
{% if messages %}
    {% for message in messages %}
        <div class="card mb-4 py-0 border-left-danger">
          <div class="card-body">
            {{ message }}
          </div>
        </div>
    {% endfor %}
{% endif %}
{% load bootstrap4 %}
        <form method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
            <input type="submit" class="btn btn-success" value="Registrar">
        </form>
{% endblock %}

templates/lote/detalhes.html
{% extends "base.html" %}

{% block titulo %}
{% if lote == None %}
  Não há lote inicial cadastrado
{% else %}
  Lote {{lote}}
  <p class="m-0 h5 font-weight-regular text-gray-500">{{lote.get_status_display}}
    <a href="{% url 'lote:alterar_status' %}" class="btn btn-primary btn-circle btn-sm" value="Alterar status">
      <i class="fas fa-exchange-alt"></i>
    </a>
  </p>
{% endif %}
{% endblock %}

{% block titulo_lateral %}
{% if lote != None %}
<!-- Adicionar o botão para mudar status aqui -->
<!-- btn-primary  é o botão azul-->

  

  <a href="{% url 'lote:criar_registro_diario' %}" class="btn btn-success btn-icon-split">
    <span class="icon text-white-50">
      <i class="fas fa-plus"></i>
    </span>
    <span class="text">Registro diário</span>
  </a>
{% endif %}
{% endblock %}

{% block conteudo %}

{% if messages %}
    {% for message in messages %}
      {% if message.tags == 'error' %}
        <div class="card mb-4 py-0 border-left-danger">
          <div class="card-body">
            {{ message }}
          </div>
        </div>
      {% else %}
        <div class="card mb-4 py-0 border-left-success">
          <div class="card-body">
            {{ message }}
          </div>
        </div>
      {% endif %}
    {% endfor %}
{% endif %}

{% if lote != None %}

<div class="row">

  <div class="col-lg-6">
    <div class="card shadow mb-4">
      <!-- Card Header - Dropdown -->
      <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Informações</h6>
      </div>
      <!-- Card Body -->
      <div class="card-body">
        <p><strong>Data de chegada:</strong> {{lote.data_chegada|date:"d/m/y"}}</p>
        <p><strong>Localidade:</strong> {{lote.localidade}}</p>
        <p><strong>Aptidão:</strong> {{lote.get_aptidao_display}}</p>
        <p><strong>Raça:</strong> {{lote.get_raca_display}}</p>
        <p><strong>Quantidade inicial:</strong> {{lote.quantidade_aves_chegada}}</p>
        <p style="color: #4e73df"><strong>Quantidade atual:</strong> {{lote.quantidade_aves_final}}</p>
      </div>
    </div>

  </div>

    <!-- Gráfico da mortalidade -->
    <div class="col-lg-6">
      <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-primary">Mortalidade</h6>
        </div>
        <!-- Card Body -->
        <div class="card-body">
          <div class="chart-area">
            <canvas id="mortalidade_chart"></canvas>
          </div>
        </div>
      </div>

    </div>

</div>

<div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Registros diários</h6>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Data</th>
              <th>Mortalidade</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <!-- Tabela de registros diários -->
            {% for registro in registros_diarios %}
            <tr>
                <td>{{registro.data|date:"d/m/y (D)" }}</td>
                <td>{{registro.mortalidade}}</td>
                <td>
                  <!-- Botão para editar -->
                  <a href="{% url 'lote:editar_registro' pk=registro.pk %}" class="btn btn-success btn-circle btn-sm">
                    <i class="fas fa-pencil-alt"></i>
                  </a>

                  <!-- Botão para deletar -->
                  <a href="" class="btn btn-danger btn-circle btn-sm" data-toggle="modal" data-target="#fm-modal-grid-{{registro.pk}}"
                          data-tt="tooltip" title="Deletar">
                      <i class="fa fa-trash" aria-hidden="true"></i>
                  </a>

                  <!-- Modal do deletar -->
                  <div class="modal fade" id="fm-modal-grid-{{registro.pk}}" tabindex="-1"
                        role="dialog" aria-labelledBy="fm-modal-grid-{{registro.pk}}"
                      aria-hidden="true">
                      <div class="modal-dialog modal-lg">
                          <div class="modal-content">
                              <div class="modal-header" style="background-color:#4e73df">
                                  <h5 class="modal-title" id=""><strong><font color="white">Você tem certeza que deseja apagar este registro?</font></strong></h5>
                                  <button class="close" data-dismiss="modal" aria-label="Cerrar">
                                      <span aria-hidden="true">&times;</span>
                                  </button>
                              </div>
                              <div class="modal-body">
                                  <div class="container">
                                      <div class="row">
                                          <div class="col-lg-4">
                                              <p><strong>Data:</strong> {{registro.data|date:"d/m/y"}}</p>
                                          </div>

                                          <div class="col-lg-4">
                                              <p><strong>Mortalidade:</strong> {{registro.mortalidade}}</p>
                                          </div>

                                          <div class="col-lg-4">
                                              <p><strong>Peso:</strong> {{registro.peso}}</p>
                                          </div>
                                      </div>
                                  </div>
                              </div>

                              <div class="modal-footer" style="background-color: rgb(78,115,223);">
                                  <form action="{% url 'lote:deletar_registro' pk=registro.pk %}" method="POST">
                                          {% csrf_token %}
                                          <button class="btn btn-danger">Deletar</button>
                                  </form>
                                  <button class="btn btn-dark" data-dismiss="modal">Cancelar</button>

                              </div>
                          </div>
                      </div>
                  </div>
                </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>


  <a href="{% url 'producao:cadastrar' %}" class="btn btn-primary btn-icon-split">
    <span class="icon text-white-50">
      <i class="fas fa-egg"></i>
    </span>
    <span id="teste" class="text">Enviar para postura</span>
  </a>
  <a href="{% url 'lote:listar_finalizados' %}" class="btn btn-danger btn-icon-split">
    <span class="icon text-white-50">
      <i class="fas fa-window-close"></i>
    </span>
    <span class="text">Acessar lotes finalizados</span>
  </a>

{% endif %}
<script>
  window.onload = function () {
    var ctx1 = document.getElementById("mortalidade_chart").getContext('2d');
    var grafico1 = new Chart(ctx1, {
        type: 'line',
        data: {
            labels: {{  datas_mortalidade | safe }},
            datasets: [
            {
                label: '#Mortalidade',
                data: {{ mortalidade | safe }},
                backgroundColor: 'rgba(74, 111, 220, 0)',
                borderColor: '#007bff',
                borderWidth: 2.5
            }
            ]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            },
            responsive: true,
            maintainAspectRatio: false,
        }
    });
    var ctx2 = document.getElementById("pesos_chart").getContext('2d');
    var grafico2 = new Chart(ctx2, {
        type: 'line',
        data: {
            labels: {{  datas_peso | safe }},
            datasets: [
            {
                label: 'Peso (kg)',
                data: {{ pesos | safe }},
                backgroundColor: 'rgba(74, 111, 220, 0)',
                borderColor: '#1cc88a',
                borderWidth: 2.5
            }
            ]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });
    grafico1.render();
    grafico2.render();
  }
</script>

{% endblock %}

templates/lote/detalhes_finalizado.html
{% extends "base.html" %}

{% block titulo %}
  Lote {{lote}}
  <p class="m-0 h5 font-weight-regular text-gray-500">{{lote.get_status_display}}</p>
{% endblock %}

{% block conteudo %}

<div class="row">

  <div class="col-lg-6">
    <div class="card shadow mb-4">
      <!-- Card Header - Dropdown -->
      <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Informações</h6>
      </div>
      <!-- Card Body -->
      <div class="card-body">
        <p><strong>Data de chegada:</strong> {{lote.data_chegada|date:"d/m/y"}}</p>
        <p><strong>Localidade:</strong> {{lote.localidade}}</p>
        <p><strong>Aptidão:</strong> {{lote.get_aptidao_display}}</p>
        <p><strong>Raça:</strong> {{lote.get_raca_display}}</p>
        <p><strong>Quantidade inicial:</strong> {{lote.quantidade_aves_chegada}}</p>
        <p style="color: #4e73df"><strong>Quantidade final:</strong> {{lote.quantidade_aves_final}}</p>
      </div>
    </div>

  </div>

    <!-- Gráfico da mortalidade -->
    <div class="col-lg-6">
      <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-primary">Mortalidade</h6>
        </div>
        <!-- Card Body -->
        <div class="card-body">
          <div class="chart-area">
            <canvas id="mortalidade_chart"></canvas>
          </div>
        </div>
      </div>

    </div>
</div>

<div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Registros diários</h6>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Data</th>
              <th>Mortalidade</th>
            </tr>
          </thead>
          <tbody>
            <!-- Tabela de registros diários -->
            {% for registro in registros_diarios %}
            <tr>
                <td>{{registro.data|date:"d/m/y (D)" }}</td>
                <td>{{registro.mortalidade}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
  
<script>
  window.onload = function () {
    var ctx1 = document.getElementById("mortalidade_chart").getContext('2d');
    var grafico1 = new Chart(ctx1, {
        type: 'line',
        data: {
            labels: {{  datas_mortalidade | safe }},
            datasets: [
            {
                label: '#Mortalidade',
                data: {{ mortalidade | safe }},
                backgroundColor: 'rgba(74, 111, 220, 0)',
                borderColor: '#007bff',
                borderWidth: 2.5
            }
            ]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            },
            responsive: true,
            maintainAspectRatio: false,
        }
    });
    var ctx2 = document.getElementById("pesos_chart").getContext('2d');
    var grafico2 = new Chart(ctx2, {
        type: 'line',
        data: {
            labels: {{  datas_peso | safe }},
            datasets: [
            {
                label: 'Peso (kg)',
                data: {{ pesos | safe }},
                backgroundColor: 'rgba(74, 111, 220, 0)',
                borderColor: '#1cc88a',
                borderWidth: 2.5
            }
            ]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });
    grafico1.render();
    grafico2.render();
  }
</script>

{% endblock %}

templates/lote/listar_finalizados.html
{% extends "base.html" %}

{% block titulo %}
  Lotes Finalizados
{% endblock %}

{% block conteudo %}
  
<!-- Informações gerais -->

<div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Lotes</h6>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Lote</th>
              <th>Data de abertura</th>
              <th>Quantidade de aves final</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <!-- Tabela de registros diários -->
            {% for lote in lista_lotes %}
            <tr>
                <td>{{lote}}</td>
                <td>{{lote.data_chegada|date:"d/m/y" }}</td>
                <td>{{lote.quantidade_aves_final}}</td>
                <td>
                  <a href="{% url 'lote:detalhes_finalizado' pk=lote.pk %}" class="btn btn-primary btn-circle btn-sm">
                    <i class="fas fa-search"></i>
                  </a>
                </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

{% endblock %}