SigAv/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lote/', include('lote.urls')),
    path('producao/', include('producao.urls')),
    path('', include('producao.urls', namespace='home')),
    path('vacina/', include('vacina.urls')),
    path('usuario/', include('usuario.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
]

lote/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'lote'

urlpatterns = [
    path('criar/', views.criar_lote, name='criar'),
    path('listar/', views.ListarLotes.as_view(), name='listar'),
    path('listar_finalizados/', views.listar_finalizados, name='listar_finalizados'),
    path('editar/<int:pk>', views.EditarLote.as_view(), name='editar'),
    path('deletar/<int:pk>', views.DeletarLote.as_view(), name='deletar'),
    path('detalhes/', views.detalhes, name='detalhes'),
    path('detalhes_finalizado/<int:pk>', views.detalhes_finalizado, name='detalhes_finalizado'),

    path('criar_registro_diario_lote/', views.criar_registro_diario, name='criar_registro_diario'),
    path('editar_registro/<int:pk>/', views.EditarRegistroDiario.as_view(), name='editar_registro'),
    path('deletar_registro/<int:pk>/', views.DeletarRegistroDiario.as_view(), name='deletar_registro'),


    path('alterar_status/', views.alterar_status, name="alterar_status"),
]

producao/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.views.generic import RedirectView

app_name = 'producao'

urlpatterns = [
    path ('', views.home, name='home'),
    path('criar/', views.Criar_Producao.as_view(), name='criar'),
    path('listar/', views.Listar_Producao.as_view(), name='listar'),
    path('editar/<int:pk>', views.Editar_Producao.as_view(), name='editar'),
    path('deletar/<int:pk>', views.Deletar_Producao.as_view(), name='deletar'),
    path('detalhes/<int:pk>', views.detalhes, name='detalhes'),

    path('criar_registro_diario_producao_1/<int:pk>/<int:tipo>', views.criar_registro_diario_1, name='criar_registro_diario_1'),
    path('criar_registro_diario_producao_2/<int:pk>', views.criar_registro_diario_2, name='criar_registro_diario_2'),

    path('editar_registro/<int:pk>/', views.EditarRegistroDiario.as_view(), name='editar_registro'),
    path('deletar_movimento_diario/<int:pk>/', views.DeletarMovimentoDiario.as_view(), name='deletar_movimento_diario'),
 
    path('cadastrar/', views.cadastrar, name='cadastrar'),
    path('alterar_status/<int:pk>', views.alterar_status, name='alterar_status'),

    path('coleta_diaria/<int:pk>', views.coleta_diaria, name='coleta_diaria'),
]

# Coleta dos bolsistas
urlpatterns += [
    path('bolsista_coleta_diaria_1/<int:pk>/<int:tipo>', views.criar_registro_diario_1, name='bolsista_coleta_diaria_1'),
    path('bolsista_coleta_diaria_2/<int:pk>', views.criar_registro_diario_2, name='bolsista_coleta_diaria_2')
]

# url patterns das novas views
urlpatterns += [
    path('bolsista/', views.home_bolsista, name='bolsista'),
    path('', views.home_admin, name='home_admin')
]

templates/bolsista/coleta_diaria.html
{% extends 'base_simplificada.html' %}
{% load bootstrap4 %}

{% block titulo_lateral %}
<a href="{% url 'producao:bolsista' %}" class="btn btn-danger btn-icon-split">
  <span class="icon text-white-50">
    <i class="fas fa-arrow-circle-left"></i>
  </span>
  <span class="text">Voltar</span>
</a>
{% endblock %}

{% block conteudo %}
<div class="row" style="justify-content: center;">

  
     <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-left-success shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="h5 font-weight-bold text-success text-uppercase mb-4">Ultima Coleta: {{ mov_diario.data }}</div>
              <div class="h6 mb-0 text-gray-800">
                <h6 class="font-weight-bold">Quantidade de ovos: {{ total_ovos }}</h6> 
                <h6 class="font-weight-bold">
                  Ovos quebrados: 
                  {% if mov_diario.0.ovos_quebrados == None %}
                    0
                  {% else %}
                    {{mov_diario.0.ovos_quebrados}}
                  {% endif %}</h6>
                <h6 class="font-weight-bold">Mortalidade: 
                  {% if mov_diario.0.mortalidade == None %}
                  0
                  {% else %}
                  {{mov_diario.0.mortalidade}}
                  {% endif %}</h6>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  
      <div class="col-xl-3 col-md-6 mb-4">
      <a href="{% url 'producao:bolsista_coleta_diaria_1' pk=producao.id tipo=2 %}" class="text-decoration-none">
        <div class="card border-left-primary shadow h-100 py-2">
              <div class="card-body">
                  <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                      <div class="h5 font-weight-bold  text-primary text-uppercase mb-4">1ª Coleta do Dia</div>
                      <div class="h6 mb-0 text-gray-800">
                          {% if mov_diario|length > 0 %}
                              Quantidade de ovos: {{ mov_diario.0.primeira_coleta }}
                          {% else %}
                              Coleta não realizada
                          {% endif %}
                      </div>
                  </div>
                  <div class="col-auto">
                      <i class="fas fa-egg fa-2x" style="color:#007bff"></i>
                  </div>
                  </div>
            </div>
        </div>
    </a>
    </div>
  
  
    <div class="col-xl-3 col-md-6 mb-4">
      <a href="{% url 'producao:bolsista_coleta_diaria_2' pk=producao.id %}" class="text-decoration-none">
      <div class="card border-left-info shadow h-100 py-2">
        <div class="card-body" style="">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="h5 font-weight-bold text-info text-uppercase mb-4">2ª Coleta do Dia</div>
              <div class="h6 mb-0 text-gray-800">
                  {% if mov_diario|length > 0 %}
                      Quantidade de ovos: 
                      {% if mov_diario.0.segunda_coleta == None %}
                        0
                      {% else %}
                        {{mov_diario.0.segunda_coleta}}
                      {% endif %}
                  {% else %}
                      Coleta não realizada
                  {% endif %}
              </div>
            </div>
            <div class="col-auto">
              <i class="fas fa-egg  fa-2x" style="color:#36b9cc"></i>
            </div>
          </div>
        </div>
      </div>
      </a>
    </div>
  </div>
 
 


{% endblock %}

templates/bolsista/criar_registro_diario.html
{% extends "base_simplificada.html" %}
{% block titulo %}
Registro diário
<p class="m-0 h5 font-weight-regular text-gray-500">Lote {{lote}}</p>

{% endblock %}

{% block titulo_lateral %}
<a href="{% url 'producao:coleta_diaria' pk=producao.id %}" class="mb-4 btn btn-danger btn-icon-split">
  <span class="icon text-white-50">
    <i class="fas fa-arrow-circle-left"></i>
  </span>
  <span class="text">Voltar</span>
</a>
{% endblock %}

{% block conteudo %}     

{% if messages %}
    {% for message in messages %}
        <div class="card mb-3 py-0 border-left-danger">
          <div class="card-body">
            {{ message }}
          </div>
        </div>
    {% endfor %}
{% endif %}

{% load bootstrap4 %}
        <form method="post" >
          {% csrf_token %}
          <div class="col-md-6 justify-content-md-center">
            {% bootstrap_form form %}
          </div>
            <input type="submit" class="btn btn-success mb-4" value="Registrar">
        </form>
{% endblock %}