SigAv/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lote/', include('lote.urls')),
    path('producao/', include('producao.urls')),
    path('', include('producao.urls', namespace='home')),
    path('vacina/', include('vacina.urls')),
    path('usuario/', include('usuario.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
]

lote/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'lote'

urlpatterns = [
    path('criar/', views.criar_lote, name='criar'),
    path('listar/', views.ListarLotes.as_view(), name='listar'),
    path('listar_finalizados/', views.listar_finalizados, name='listar_finalizados'),
    path('editar/<int:pk>', views.EditarLote.as_view(), name='editar'),
    path('deletar/<int:pk>', views.DeletarLote.as_view(), name='deletar'),
    path('detalhes/', views.detalhes, name='detalhes'),
    path('detalhes_finalizado/<int:pk>', views.detalhes_finalizado, name='detalhes_finalizado'),

    path('criar_registro_diario_lote/', views.criar_registro_diario, name='criar_registro_diario'),
    path('editar_registro/<int:pk>/', views.EditarRegistroDiario.as_view(), name='editar_registro'),
    path('deletar_registro/<int:pk>/', views.DeletarRegistroDiario.as_view(), name='deletar_registro'),


    path('alterar_status/', views.alterar_status, name="alterar_status"),
]

producao/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.views.generic import RedirectView

app_name = 'producao'

urlpatterns = [
    path ('', views.home, name='home'),
    path('criar/', views.Criar_Producao.as_view(), name='criar'),
    path('listar/', views.Listar_Producao.as_view(), name='listar'),
    path('editar/<int:pk>', views.Editar_Producao.as_view(), name='editar'),
    path('deletar/<int:pk>', views.Deletar_Producao.as_view(), name='deletar'),
    path('detalhes/<int:pk>', views.detalhes, name='detalhes'),

    path('criar_registro_diario_producao_1/<int:pk>/<int:tipo>', views.criar_registro_diario_1, name='criar_registro_diario_1'),
    path('criar_registro_diario_producao_2/<int:pk>', views.criar_registro_diario_2, name='criar_registro_diario_2'),

    path('editar_registro/<int:pk>/', views.EditarRegistroDiario.as_view(), name='editar_registro'),
    path('deletar_movimento_diario/<int:pk>/', views.DeletarMovimentoDiario.as_view(), name='deletar_movimento_diario'),
 
    path('cadastrar/', views.cadastrar, name='cadastrar'),
    path('alterar_status/<int:pk>', views.alterar_status, name='alterar_status'),

    path('coleta_diaria/<int:pk>', views.coleta_diaria, name='coleta_diaria'),
]

# Coleta dos bolsistas
urlpatterns += [
    path('bolsista_coleta_diaria_1/<int:pk>/<int:tipo>', views.criar_registro_diario_1, name='bolsista_coleta_diaria_1'),
    path('bolsista_coleta_diaria_2/<int:pk>', views.criar_registro_diario_2, name='bolsista_coleta_diaria_2')
]

# url patterns das novas views
urlpatterns += [
    path('bolsista/', views.home_bolsista, name='bolsista'),
    path('', views.home_admin, name='home_admin')
]

usuario/urls.py
#from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.urls import path

from usuario import views

app_name = 'usuario'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='usuario/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('cadastrar/', views.CadastrarUsuario.as_view(), name='cadastrar'),
    path('editar/<int:pk>', views.EditarUsuario.as_view(), name = 'editar'),
    path('listar/', views.listar, name='listar'),
    path('listar_inativos/', views.listar_inativos, name='listar_inativos'),
    path('alterar_status/<int:status>/<int:pk>', views.alterar_status, name='alterar_status'),
]

vacina/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'vacina'

urlpatterns = [
    path('criar/', views.CriarVacina.as_view(), name='criar'),
    path('listar/', views.ListarVacina.as_view(), name='listar'),
    path('editar/<int:pk>', views.EditarVacina.as_view(), name='editar'),
    path('deletar/<int:pk>', views.DeletarVacina.as_view(), name='deletar'),
    path('detalhes/<int:pk>', views.DetalharVacina.as_view(), name='detalhes'),
]

producao/models.py
from django.db import models
from datetime import date
from lote.models import Lote #importa a classe que stá sendo referênciada através da chave estrangeira

TIPODECRIACAO = [
    ('A', 'Cage free'),
    ('B', 'Gaiolas'),
    ('C', 'Caipira'),
]

STATUS = [
    ('A', 'Ativo'),
    ('B', 'Inativo'),
]

class Fase_postura(models.Model):
    
    lote = models.ForeignKey(Lote, on_delete=models.RESTRICT)
    tipo_sistema = models.CharField(max_length=1, choices=TIPODECRIACAO)
    data_chegada = models.DateField(default=date.today)
    quantidade_aves_chegada = models.PositiveIntegerField()
    quantidade_aves_final = models.PositiveIntegerField(null=True, blank=True)
    media_postura_diaria = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    status = models.CharField(max_length=1, choices=STATUS, default='A') # Representa a existência ou não das aves no ambiente
    observacoes = models.CharField(max_length=400, null=True, blank=True)

    def __str__(self):
        return self.tipo_sistema
    
    class Meta:
        ordering = ('status','tipo_sistema',)

class Movimento_diario_postura(models.Model):
    
    fase_postura = models.ForeignKey(Fase_postura, on_delete=models.RESTRICT)
    data = models.DateField(default=date.today)
    mortalidade = models.PositiveIntegerField(default=0)
    primeira_coleta = models.PositiveIntegerField(null=True)
    segunda_coleta = models.PositiveIntegerField()
    ovos_quebrados = models.PositiveIntegerField(default=0)
    percentual_postura = models.PositiveIntegerField(null=True, blank=True) # Valor calculado automaticamente

    def __str__(self):
        return "Fase_postura: {}, Data: {}".format(str(self.fase_postura), str(self.data))
    
    class Meta:
        ordering = ('fase_postura', 'data',)

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SigAviário</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/startbootstrap-sb-admin-2/4.1.4/css/sb-admin-2.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/startbootstrap-sb-admin-2/4.1.4/css/sb-admin-2.css">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/startbootstrap-sb-admin-2/4.1.4/js/sb-admin-2.min.js"></script>
  <!-- Custom styles for this template-->

  <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/sb-admin-2.css' %}" />  -->

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">
    <!-- Menu lateral -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'producao:home_admin' %}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-egg"></i>
        </div>
        <div class="sidebar-brand-text mx-3">SigAviário</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'producao:home_admin' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Home</span></a>
      </li>



      <!-- Divider -->
      <hr class="sidebar-divider">

            <!-- Heading -->
      <div class="sidebar-heading">
        Registros diários
      </div>

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'lote:detalhes'%}">
          <i class="fas fa-border-all"></i>
          <span>Lote inicial</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'producao:listar'%}">
          <i class="fas fa-egg"></i>
          <span>Lote de produção</span>
        </a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <!--<div class="sidebar-heading">
        Lotes
      </div>-->
    
    
     <!--<li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'lote:criar' %}">
          <i class="fas fa-plus"></i>
          <span>Abertura de Lote</span>
        </a>
      </li>-->

        <!-- Heading -->
        <div class="sidebar-heading">
        Cadastro
        </div>

        <li class="nav-item">
          <a class="nav-link collapsed" href="{% url 'lote:criar' %}">
            <i class="fas fa-plus"></i>
            <span>Lote inicial</span>
          </a>
        </li>

        {% if user.is_staff %}
          <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'vacina:criar' %}">
              <i class="fas fa-syringe"></i>
              <span>Vacina</span>
            </a>
          </li>
        {% endif %}
           
      
       <hr class="sidebar-divider">


       <div class="sidebar-heading">
        Usuarios
      </div>

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'usuario:cadastrar' %}">
          <i class="fas fa-plus"></i>
          <span>Cadastrar</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUser" aria-expanded="true" aria-controls="collapseUtilities">
          <i class="fas fa-users"></i>
          <span>Listar Usuarios</span>
        </a>
        <div id="collapseUser" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
             <h6 class="collapse-header">Situação:</h6>
            <a class="collapse-item" href="{% url 'usuario:listar' %}">Ativos</a>
            <a class="collapse-item" href="{% url 'usuario:listar_inativos' %}">Inativos</a>
          </div>
        </div>
      </li>

      


      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">
            
            <!-- Nav Item - Alerts -->



            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-lg-inline text-gray-600 small">{{user.first_name}} {{user.last_name}}</span>
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'usuario:editar' pk=user.pk %}">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Minha conta
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'usuario:logout' %}">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">
              {% block titulo %}

              {% endblock %}
            </h1>

            <div>
              {% block titulo_lateral %}
              {% endblock %}
            </div>
          </div>

          {% block conteudo %}
          <!--Dentro dele, sempre usar <div class="row"> para separar elementos em uma mesma linha-->
          {% endblock %}
          <!-- Content Row -->

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span> SigAv EAJ/UFRN</span>
 
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  {% block extra_js %}
  {% endblock %}

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.js' %}"></script>

  <!-- Page level plugins -->
  <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

  <!-- Page level custom scripts -->
  <!-- <script src="{% static 'js/demo/chart-area-demo.js' %}"></script> -->
  <!-- <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script> -->

  <script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
  <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
  <script src="{% static 'js/demo/datatables-demo.js' %}"></script>

</body>

</html>

templates/base_simplificada.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SigAviário | Bolsista</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/startbootstrap-sb-admin-2/4.1.4/css/sb-admin-2.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/startbootstrap-sb-admin-2/4.1.4/css/sb-admin-2.css">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/startbootstrap-sb-admin-2/4.1.4/js/sb-admin-2.min.js">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/startbootstrap-sb-admin-2/4.1.4/js/sb-admin-2.min.js"></script>
  
  <!-- Custom styles for this template-->

 
  <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/sb-admin-2.css' %}" /> -->

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">
      <!-- Main Content -->
      <div id="content">
        <!-- Topbar -->
        <header class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">
            <!-- Nav Item - Alerts -->
            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-lg-inline text-gray-600 small">{{user.first_name}} {{user.last_name}}</span>
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'usuario:logout' %}">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>
          </ul>
        </header>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">
              {% block titulo %}

              {% endblock %}
            </h1>

            <div>
              {% block titulo_lateral %}
              {% endblock %}
            </div>
          </div>

          {% block conteudo %}
          <!--Dentro dele, sempre usar <div class="row"> para separar elementos em uma mesma linha-->
          {% endblock %}
          <!-- Content Row -->

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span> SigAv EAJ/UFRN</span>
 
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  {% block extra_js %}
  {% endblock %}

  <!-- Bootstrap core JavaScript-->
  
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.js' %}"></script>

  <!-- Page level plugins -->
  <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

  <!-- Page level custom scripts -->
  <!-- <script src="{% static 'js/demo/chart-area-demo.js' %}"></script> -->
  <!-- <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script> -->

  <script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
  <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
  <script src="{% static 'js/demo/datatables-demo.js' %}"></script>
</body>

</html>

templates/home_bolsista.html
{% extends 'base_simplificada.html' %}
{% load bootstrap4 %}


{% block conteudo %}
<div class="row"  style="justify-content:center">

  {% for producao in lista_producoes %}
       {%if forloop.counter0|divisibleby:2 %}
        <br>
       <div class="col-10 btn-toolbar" style="justify-content:center; margin-bottom: 2.5rem">

       {%endif%}

                <!-- Earnings (Monthly) Card Example -->
                {%  if producao.tipo_sistema == "A" %}
                <div class="col-lg-4 col-md-6">
                  <a href="{% url 'producao:detalhes' pk=producao.id %}" style="text-decoration: none;">
                    <div class="card border-left-primary shadow h-100 py-2">
                      <div class="card-body">
                        <div class="row no-gutters align-items-center" style="display: flex;">
                          <div class="col mr-2">
                            <div class="text-m font-weight-bold text-primary text-uppercase mb-1">{{producao.get_tipo_sistema_display}}</div>
                            <div class="mb-0 text-gray-800"><strong>Data de chegada:</strong> {{producao.lote}}</div>
                            
                          
                            <div class="mb-0 text-gray-800"><strong>Data de chegada:</strong> {{producao.data_chegada|date:"d/m/y"}}</div>
                            <div class="mb-0 text-gray-800"><strong>Quantidade:</strong> {{producao.quantidade_aves_final}}</div>
                            
                          
                          </div>
                          <div class="col-auto">
                            <i class="fas fa-kiwi-bird fa-3x" style="color:#007bff"></i>
                            
                          </div>
                        </div>
                      </div>
                    </div>
                  </a>
                </div>
                {% elif producao.tipo_sistema == "B"%}
              
    
                <!-- Earnings (Monthly) Card Example -->

                <div class="col-lg-4 col-md-6">
                  <a href="{% url 'producao:coleta_diaria' pk=producao.id %}" style="text-decoration: none;">
                  <div class="card border-left-success shadow h-100 py-2">
                    <div class="card-body">
                      <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                          <div class="text-m font-weight-bold text-success text-uppercase mb-1">{{producao.get_tipo_sistema_display}}</div>
                         
                         
                          <div class="mb-0 text-gray-800"><strong>Data de chegada:</strong> {{producao.data_chegada|date:"d/m/y"}}</div>
                          <div class="mb-0 text-gray-800"><strong>Quantidade:</strong> {{producao.quantidade_aves_final}}</div>
                          
                        
                        </div>
                        <div class="col-auto">
                          <i class="fas fa-border-all fa-3x" style="color:#28a745"></i>
                        </div>
                      </div>
                    </div>
                  </div>
                </a>
                </div>

                {% else %}

                
                <div class="col-lg-4 col-md-6">
                  <a href="{% url 'producao:detalhes' pk=producao.id %}" style="text-decoration: none;">
                  <div class="card border-left-info shadow h-100 py-2">
                    <div class="card-body">
                      <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                          <div class="text-m font-weight-bold text-info text-uppercase mb-1">{{producao.get_tipo_sistema_display}}</div>
                          
                         
                          <div class="mb-0 text-gray-800"><strong>Data de chegada:</strong> {{producao.data_chegada|date:"d/m/y"}}</div>
                          <div class="mb-0 text-gray-800"><strong>Quantidade:</strong> {{producao.quantidade_aves_final}}</div>
                          
                       
                        </div>
                        <div class="col-auto">
                          <i class="fab fa-pagelines fa-3 fa-3x" style="color:#17a2b8"></i>
                          
                        </div>
                      </div>
                    </div>
                  </div>
                </a>
                </div>
    
               {%endif%}
               

          {%if forloop.counter|divisibleby:3 %}
    
        </div>
        {% endif %}

        {% endfor %}

  <!-- <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-primary shadow h-100 py-2">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="h5 font-weight-bold text-primary text-uppercase mb-4">1ª Coleta do Dia</div>
                <div class="h6 mb-0 font-weight-bold text-gray-800">Realizar primeira coleta</div>
              </div>
              <div class="col-auto">
                <i class="fas fa-egg fa-2x" style="color:#007bff"></i>
              </div>
            </div>
        </div>
    </div>
  </div> -->


  <!-- <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-info shadow h-100 py-2">
      <div class="card-body" style="">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="h5 font-weight-bold text-info text-uppercase mb-4">2ª Coleta do Dia</div>
            <div class="h6 mb-0 font-weight-bold text-gray-800">Realizar segunda coleta</div>
          </div>
          <div class="col-auto">
            <i class="fas fa-egg  fa-2x" style="color:#36b9cc"></i>
          </div>
        </div>
      </div>
    </div>
  </div> -->

{% endblock %}