SigAv/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lote/', include('lote.urls')),
    path('producao/', include('producao.urls')),
    path('', include('producao.urls', namespace='home')),
    path('vacina/', include('vacina.urls')),
    path('usuario/', include('usuario.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
]

lote/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'lote'

urlpatterns = [
    path('criar/', views.criar_lote, name='criar'),
    path('listar/', views.ListarLotes.as_view(), name='listar'),
    path('listar_finalizados/', views.listar_finalizados, name='listar_finalizados'),
    path('editar/<int:pk>', views.EditarLote.as_view(), name='editar'),
    path('deletar/<int:pk>', views.DeletarLote.as_view(), name='deletar'),
    path('detalhes/', views.detalhes, name='detalhes'),
    path('detalhes_finalizado/<int:pk>', views.detalhes_finalizado, name='detalhes_finalizado'),

    path('criar_registro_diario_lote/', views.criar_registro_diario, name='criar_registro_diario'),
    path('editar_registro/<int:pk>/', views.EditarRegistroDiario.as_view(), name='editar_registro'),
    path('deletar_registro/<int:pk>/', views.DeletarRegistroDiario.as_view(), name='deletar_registro'),


    path('alterar_status/', views.alterar_status, name="alterar_status"),
]

vacina/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'vacina'

urlpatterns = [
    path('criar/', views.CriarVacina.as_view(), name='criar'),
    path('listar/', views.ListarVacina.as_view(), name='listar'),
    path('editar/<int:pk>', views.EditarVacina.as_view(), name='editar'),
    path('deletar/<int:pk>', views.DeletarVacina.as_view(), name='deletar'),
    path('detalhes/<int:pk>', views.DetalharVacina.as_view(), name='detalhes'),
]

vacina/models.py
from django.db import models
from datetime import date
from lote.models import Lote #importa a classe que stá sendo referênciada através da chave estrangeira
 
# essas aplicações (tipos de vacina), foram inseridas aqui baseadas do 
# no site da embarapa 
# link: https://www.agencia.cnptia.embrapa.br/gestor/frango_de_corte/arvore/CONT000fc6gr40002wx5eo0a2ndxypswho8b.html

APLICACAO = [

    ('A', 'Doença de Marek'),
    ('B', 'Doença de Gumboro'),
    ('C', 'Varíola Aviária'),
    ('D', 'Bronquite infecciosa das Galinhas'),
    ('E', 'Doença de Newcastle')
]

ADMINISTRACAO = [

    ('A', 'Oral'),
    ('B', 'Injetavél'),
    ('C', 'Membrana da Asa'),
]
class Vacina(models.Model):
    
    tipo  = models.CharField(max_length=1, choices=APLICACAO)
    doses = models.CharField(max_length=1, choices=ADMINISTRACAO)

    def __str__(self):
        return self.tipo
        
    class Meta:
        ordering = ('tipo', 'doses')

class AplicacaoVacina(models.Model):
    
    id_vacina = models.ForeignKey   (Vacina, on_delete=models.RESTRICT)
    id_lote = models.ForeignKey(Lote, on_delete=models.RESTRICT)
    data = models.DateField(default=date.today)
    observacoes = models.CharField(max_length=400, null=True, blank=True)
      
    def __str__ (self):
        return str(self.vacina) + " - " + str(self.id_lote)
        
    class Meta:
        ordering = ('data','observacoes')

class TempoVacinacao(models.Model):
    
    id_vacina = models.ForeignKey(Vacina, on_delete=models.RESTRICT)
    via_administracao = models.CharField(max_length=1, choices=ADMINISTRACAO)
    periodo_administracao = models.CharField(max_length=100)

    def __str__(self):
        return str(self.via_administracao) 

    class Meta:
        ordering= ('via_administracao', 'periodo_administracao')

vacina/forms.py
from django import forms
from django.forms import ModelForm
from django.db.models import Q
from django.core.exceptions import ValidationError
from .models import Vacina, AplicacaoVacina, TempoVacinacao
from datetime import date


class VacinaForm(ModelForm):
  class Meta:
    model = Vacina
    fields = ['tipo', 'doses']


class AplicacaoVacinaForm(ModelForm):
  
  class Meta:
    model = AplicacaoVacina
    fields = ['data', 'observacoes']

  def __init__(self, vacina_id, *args, **kwargs):
    self.vacina_id = vacina_id
    super(AplicacaoVacina, self).__init__(*args, **kwargs)
  

  def clear_data(self):
    data = self.cleaned_data['data']

    if data > date.today() :
      raise forms.ValidationError("Não é possível realizar um registro para uma data futura.")
    elif (len(AplicacaoVacina.objects.filter(data=data, observacoes=observacoes)) > 0):
      raise forms.ValidationError("Uma vacina já foi realiza nesse lote")


class TempoVacinacaoForm(ModelForm):
  
  class Meta:
    model = TempoVacinacao
    fields = ['via_administracao', 'periodo_administracao']

vacina/views.py
from django.db import connection
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

import vacina

from .forms import AplicacaoVacinaForm, TempoVacinacaoForm, VacinaForm
from .models import AplicacaoVacina, TempoVacinacao, Vacina


class CriarVacina(CreateView):
    model = Vacina
    fields = ['tipo', 'doses']
    template_name = 'vacina/criar.html'
    # form

    def get_success_url(self):
        return reverse_lazy('vacina:listar')


class ListarVacina(ListView):
    model = Vacina
    template_name = 'vacina/listar.html'
    # lote_list


class EditarVacina(UpdateView):
    model = Vacina
    fields = ['tipo', 'doses']
    template_name = 'vacina/editar.html'
    success_url = reverse_lazy('vacina:listar')
    # form


class DeletarVacina(DeleteView):
    model = Vacina
    template_name = 'vacina/confirmacao_deletar.html'
    success_url = reverse_lazy('vacina:listar')
    # object


class DetalharVacina(DetailView):
    model = Vacina
    template_name = 'vacina/detalhes.html'
    # object


def Vacina(request):
    if(request.method == "POST"):
        form = VacinaForm(request.POST)
        if(form.is_valid()):
            vacina = Vacina()
            vacina.tipo = form.cleaned_data['tipo']
            vacina.doses = form.cleaned_data['doses']
        return render(request, 'vacina/criar')

templates/vacina/confirmacao_deletar.html
{% extends "base.html" %}

{% block titulo %}
Deletar registro
{% endblock %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    {% block conteudo %}
    {% load bootstrap4 %}
</head>
<body>
    <div class="container">

        <form method="post">
            {% csrf_token %}
            Lote: {{object}} <br>
            Data: {{object.data_chegada}} <br>
            Localidade: {{object.localidade}} <br>
            <input type="submit" class="btn btn-success" value="Deletar">
        </form>
      </div>
</body>
</html>
{% endblock %}

templates/vacina/criar.html
{% extends "base.html" %}

{% block titulo %}
Tipo de Vacina
{% endblock %}

  {% block titulo_lateral %}
  <li style="list-style-type: none">
    <a class="btn btn-info btn-icon-split" href="{% url 'vacina:listar' %}">
      <span class="icon text-white-50">
        <i class="fas fa-info-circle"></i>
      </span>
      <span class="text">Vacinas Realizadas</span>
    </a>
  </li>

  {% endblock %}

  {% block conteudo %}
  {% load bootstrap4 %}

  <div class="container">

    <form method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-success" value="Cadastrar">
    </form>
  </div>

{% endblock %}

templates/vacina/detalhes.html
{% extends "base.html" %}

{% block titulo %}
Detalhes do registro
{% endblock %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    {% block conteudo %}
    {% load bootstrap4 %}
</head>
<body>
    <h1>Lote {{object}}</h1>
    
    Data: {{object.data_chegada}} <br>
    Localidade: {{object.localidade}} <br>
</body>
</html>

{% endblock %}

templates/vacina/editar.html
{% extends "base.html" %}

{% block titulo %}
Editar Lote
{% endblock %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    {% block conteudo %}
    {% load bootstrap4 %}
</head>
<body>
    <div class="container">

        <form method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
            <input type="submit" class="btn btn-success" value="Atualizar">
        </form>
      </div>
</body>
</html>
{% endblock %}

templates/vacina/listar.html
{% extends "base.html" %}

{% block titulo %}
Tipos de vacinas
{% endblock %}


{% block titulo_lateral %}
<a href="{% url 'vacina:criar' %}" class="btn btn-danger btn-icon-split">
  <span class="icon text-white-50">
    <i class="fas fa-arrow-circle-left"></i>
  </span>
  <span class="text">Voltar</span>
</a>
{% endblock %}

{% block conteudo %}
{% if object_list %}

{% for vacina in object_list %}
{%if forloop.counter0|divisibleby:3 %}
<br>
<div class="row">
  {%endif%}

  <!-- Earnings (Monthly) Card Example -->
  <div class="col-lg-4 col-md-6 mb-4">
    <a href="" style="text-decoration: none;">
      <div class="card border-left-primary shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="text-m font-weight-bold text-primary text-uppercase mb-1">{{vacina.get_display}}</div>
              <div class="mb-0 text-gray-800"><strong>Tipo:</strong> {{vacina.get_tipo_display}}</div>
              <div class="mb-0 text-gray-800"><strong>Administração:</strong> {{vacina.get_doses_display}}</div>
            </div>
            <div class="col-auto">
              <i class="fas fa-syringe fa-3x" style="color:#007bff"></i>
            </div>
          </div>
        </div>
      </div>
    </a>
  </div>


  {%if forloop.counter|divisibleby:3 %}

</div>
{% endif %}

{% endfor %}

{% if not object_list|length|divisibleby:3 %}
</div>
{% endif %}

{% else %}
<p>Não há produção.</p>
{% endif %}


{% endblock %}